# This is a basic workflow to help you get started with Actions
name: Packj security audit

# Controls when the workflow will run
on:
  pull_request:
    branches: main

permissions:  # principle of least privilege (only code READ perms)
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "packj-audit"
  packj-security-audit:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Audit 
      - name: Audit dependencies
        uses: ossillate-inc/packj-github-action@v0.0.8-beta
        with:
          DEPENDENCY_FILES: pypi:requirements.txt
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
