# This is a basic workflow to help you get started with Actions
name: Packj security audit

# Controls when the workflow will run
on:
  # Allows non-contributors to run PR jobs
  pull_request:
    branches: main

# Declare default permissions as read only.
permissions: read-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "packj-audit"
  packj-security-audit:

    # write perms
    permissions:
      pull-requests: write

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Audit 
      - name: Audit dependencies
        uses: shivaabhishek07/packj-github-action@6cb46380428960652c9d50132bbc8be2b7508f70
        with:
          DEPENDENCY_FILES: pypi:requirements.txt
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
